import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

//html의 틀을 잡아주는 역할 (document의 역할). 절대없어지면 안되는 코드
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header>
          <Link href={"/"}> index</Link>
          &nbsp;
          <Link href={"/search"}> search</Link>
          &nbsp;
          <Link href={"book/1/"}> book1</Link>
        </header>
        {children}
      </body>
    </html>
  );
}
